spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 60011258887-nfseco8f2905gk99ocakim0l1bc0ln2n.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: awfnehjfuwifnow3ufapsduf2p3894enj           # 민감한 정보는 시스템 환경 변수에서 로드한다.
  access-token-life-time: 30
  refresh-token-life-time: 420